### ISSUE TITLE
(sharp:17721): GLib-CRITICAL **: 20:19:47.745: g_hash_table_lookup: assertion 'hash_table != NULL' failed

### ISSUE THREAD

**Issue by oscarsmeulders** [jeromecoupe/webstoemp#6]
New to a lot of coding, and i'm very interessed in 11ty in combination to gulp. 
I found your repository, but i am getting an error while running 'gulp'. 
(sharp:17721): GLib-CRITICAL **: 20:19:47.745: g_hash_table_lookup: assertion 'hash_table != NULL' failed

What it did:
- npm install
- tried: npm update

is this error familiar  to you and can you help my running your gulp?
thanks in advance!

**Comment by jeromecoupe** [comment]
Sorry not familiar to me ... did you try updating all dependencies in `package.json` then nuking both the `node_modules` and `package-lock.json` before doing a an `npm install` ?
